apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ocbc-best-practise-certexpiry
  namespace: ocbc-policies
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-8 Transmission Confidentiality and Integrity
    policy.open-cluster-management.io/description: Check certificate expiry
    policy.open-cluster-management.io/standards: NIST SP 800-53
  creationTimestamp: 2025-07-31T07:01:12Z
  generation: 1
  managedFields:
  resourceVersion: "515765"
  uid: a7348f0d-b918-4da4-ad82-51a6cbd9dd5a
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy
        metadata:
          name: policy-certificate
        spec:
          minimumDuration: 300h
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
              - openshift-ingress
          remediationAction: inform
          severity: low
