apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  annotations:
    cluster.open-cluster-management.io/submariner-broker-ns: by-dev-broker
  finalizers:
  - cluster.open-cluster-management.io/managedclusterset-clusterrole
  - cluster.open-cluster-management.io/submariner-cleanup
  generation: 1
  name: by-dev
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  annotations:
    cluster.open-cluster-management.io/submariner-broker-ns: by-prod-broker
  finalizers:
  - cluster.open-cluster-management.io/managedclusterset-clusterrole
  - cluster.open-cluster-management.io/submariner-cleanup
  generation: 1
  name: by-prod
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  annotations:
    cluster.open-cluster-management.io/submariner-broker-ns: division-payment-broker
  finalizers:
  - cluster.open-cluster-management.io/managedclusterset-clusterrole
  - cluster.open-cluster-management.io/submariner-cleanup
  generation: 1
  name: division-payment
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  annotations:
    cluster.open-cluster-management.io/submariner-broker-ns: division-retail-broker
  finalizers:
  - cluster.open-cluster-management.io/managedclusterset-clusterrole
  - cluster.open-cluster-management.io/submariner-cleanup
  generation: 1
  name: division-retail
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  annotations:
    cluster.open-cluster-management.io/submariner-broker-ns: team-elastic-broker
  finalizers:
  - cluster.open-cluster-management.io/managedclusterset-clusterrole
  - cluster.open-cluster-management.io/submariner-cleanup
  generation: 1
  name: team-elastic
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
