apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: team-elastic-placement-binding
  namespace: ocbc-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: team-elastic-placement
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: admission
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: operator
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: best-practise
