apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: OCBC Security Assessment
    policy.open-cluster-management.io/controls: SA-4 Runtime Security
    policy.open-cluster-management.io/description: Enable Gatekeeper
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: ocbc-admission
  namespace: ocbc-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1beta1
      kind: OperatorPolicy
      metadata:
        name: operatorpolicy-gatekeeper-operator
      spec:
        complianceType: musthave
        remediationAction: inform
        severity: high
        subscription:
          channel: stable
          name: gatekeeper-operator-product
          namespace: openshift-operators
          source: redhat-operators
          sourceNamespace: openshift-marketplace
          startingCSV: gatekeeper-operator-product.v3.19.0
        upgradeApproval: Automatic
        versions: null
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: gatekeeper
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.gatekeeper.sh/v1alpha1
            kind: Gatekeeper
            metadata:
              name: gatekeeper
            spec:
              audit:
                logLevel: INFO
                replicas: 1
              mutatingWebhook: Disabled
              validatingWebhook: Enabled
              webhook:
                emitAdmissionEvents: Enabled
                logLevel: INFO
                replicas: 2
        remediationAction: inform
        severity: high
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: gatekeeper-status
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Pod
            metadata:
              labels:
                control-plane: audit-controller
              namespace: openshift-gatekeeper-system
            status:
              phase: Running
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Pod
            metadata:
              labels:
                control-plane: controller-manager
              namespace: openshift-gatekeeper-system
            status:
              phase: Running
        remediationAction: inform
        severity: high
  remediationAction: enforce
