apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: OCBC Configuration Management
    policy.open-cluster-management.io/controls: CM-1 Mandatory operators
    policy.open-cluster-management.io/description: Install Local Storage operator
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: ocbc-operator-lso
  namespace: ocbc-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1beta1
      kind: OperatorPolicy
      metadata:
        name: install-operator-lso
      spec:
        complianceType: musthave
        remediationAction: inform
        severity: high
        subscription:
          channel: stable
          name: local-storage-operator
          namespace: openshift-local-storage
          source: redhat-operators
          sourceNamespace: openshift-marketplace
          startingCSV: local-storage-operator.v4.19.0-202507081507
        upgradeApproval: Automatic
        versions: null
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-namespace-lso
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: openshift-local-storage
        remediationAction: enforce
        severity: low
  remediationAction: enforce
