apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
    policy.open-cluster-management.io/description: Must Have operator
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: ocbc-operator-compliance
  namespace: ocbc-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: comp-operator-ns
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: openshift-compliance
        remediationAction: inform
        severity: high
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1beta1
      kind: OperatorPolicy
      metadata:
        name: operatorpolicy-comp-operator
      spec:
        complianceType: musthave
        operatorGroup:
          name: compliance-operator
          namespace: openshift-compliance
          targetNamespaces:
          - openshift-compliance
        remediationAction: inform
        severity: high
        subscription:
          config: '{{ if and (eq "ROSA" (fromClusterClaim "product.open-cluster-management.io"))
            (eq "true" (fromClusterClaim "hostedcluster.hypershift.openshift.io"))
            }}{"nodeSelector":{"node-role.kubernetes.io/worker":""} }{{ else }}{{
            "{}" | toLiteral }}{{ end }}'
          name: compliance-operator
          namespace: openshift-compliance
          source: redhat-operators
          sourceNamespace: openshift-marketplace
        upgradeApproval: Automatic
  remediationAction: enforce
